name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: User activity
        uses: lowlighter/metrics@latest
        with:
          filename: images/user-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
      
      - name: Most Used Languages activity
        uses: lowlighter/metrics@latest
        with:
          filename: images/most-used-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: ['c++','python','cmake','html']
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 8
          user: FMotalleb

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: images/recent-activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 0
          plugin_activity_ignored: star, comment, ref/delete
